[package]
name = "sans-io-blog-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
stun_codec = "0.3.5"
anyhow = "1"
rand = "0.8.5"
bytecodec = "0.4.15"